#!/usr/bin/env python3
"""Build deterministic PCM, installer, source, demo, and manual artifacts."""

from __future__ import annotations

import hashlib
import json
import shutil
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
VERSION = "0.0.2"
FIXED_TIMESTAMP = (2026, 8, 13, 0, 0, 0)
PLATFORMS = ("windows", "macos", "linux")

if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

from build_manuals import build_manual_files  # noqa: E402
from check_package import (  # noqa: E402
    run_optional_checks,
    validate_all_installers_archive,
    validate_archive,
    validate_default_config,
    validate_installer_archive,
    validate_manual_archive,
    validate_pcm_metadata,
    validate_plugin_manifest,
    validate_python_sources,
    validate_release_safety_contracts,
    validate_source_archive,
    validate_user_manual_archive,
)
from generate_demo import generate  # noqa: E402


def excluded(path: Path) -> bool:
    """Return whether a path is build output or local cache."""

    relative = path.relative_to(ROOT)
    parts = set(relative.parts)
    return bool(
        parts
        & {
            "dist",
            "build",
            ".venv",
            "venv",
            ".tox",
            ".nox",
            ".pytest_cache",
            ".ruff_cache",
            ".mypy_cache",
            "__pycache__",
            ".git",
            "_build",
            "_generated",
            "htmlcov",
        }
        or path.suffix in {".pyc", ".pyo"}
        or path.name in {".coverage", ".DS_Store", "Thumbs.db"}
        or any(part.endswith((".egg-info", ".dist-info")) for part in relative.parts)
        or path.name.startswith((".coverage.", ".schema-"))
    )


def add_file(archive: zipfile.ZipFile, source: Path, arcname: str) -> None:
    """Add one file with reproducible metadata."""

    info = zipfile.ZipInfo(arcname.replace("\\", "/"), FIXED_TIMESTAMP)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = (0o755 if source.stat().st_mode & 0o111 else 0o644) << 16
    archive.writestr(info, source.read_bytes())


def add_bytes(archive: zipfile.ZipFile, payload: bytes, arcname: str, mode: int = 0o644) -> None:
    """Add generated bytes with reproducible metadata."""

    info = zipfile.ZipInfo(arcname.replace("\\", "/"), FIXED_TIMESTAMP)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = mode << 16
    archive.writestr(info, payload)


def write_tree(archive: zipfile.ZipFile, source_root: Path, archive_root: str) -> None:
    """Write a directory tree while excluding caches."""

    for path in sorted(source_root.rglob("*")):
        if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc":
            relative = path.relative_to(source_root).as_posix()
            add_file(archive, path, f"{archive_root}/{relative}")


def write_plugin_payload(
    archive: zipfile.ZipFile,
    archive_root: str,
    manual_directory: Path,
) -> None:
    """Write the plugin and replace any stale embedded manuals."""

    for path in sorted((ROOT / "plugin").rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        relative = path.relative_to(ROOT / "plugin")
        if relative.parts and relative.parts[0] == "docs":
            continue
        add_file(archive, path, f"{archive_root}/{relative.as_posix()}")
    write_tree(archive, manual_directory, f"{archive_root}/docs")


def build_pcm(manual_directory: Path) -> Path:
    """Build the KiCad PCM-compatible archive."""

    output = DIST / f"openai-emi-guardian-{VERSION}-pcm.zip"
    with zipfile.ZipFile(output, "w") as archive:
        add_file(archive, ROOT / "metadata.json", "metadata.json")
        write_plugin_payload(archive, "plugins", manual_directory)
        add_file(archive, ROOT / "resources" / "icon.png", "resources/icon.png")
    return output


def build_manual(manual_directory: Path) -> Path:
    """Build a ZIP that can be extracted directly into KiCad's plugins directory."""

    output = DIST / f"emi-guardian-{VERSION}-manual-install.zip"
    with zipfile.ZipFile(output, "w") as archive:
        write_plugin_payload(archive, "emi-guardian", manual_directory)
    return output


def build_user_manuals(manual_directory: Path) -> Path:
    """Build the standalone bilingual user-manual ZIP."""

    output = DIST / f"emi-guardian-{VERSION}-user-manuals.zip"
    with zipfile.ZipFile(output, "w") as archive:
        write_tree(archive, manual_directory, "emi-guardian-user-manuals")
    return output


def build_platform_installer(platform: str, manual_directory: Path) -> Path:
    """Build one self-contained platform installer and updater archive."""

    output = DIST / f"emi-guardian-{VERSION}-{platform}-installer.zip"
    archive_root = f"emi-guardian-{VERSION}-{platform}"
    scripts_root = ROOT / "installers" / platform
    with zipfile.ZipFile(output, "w") as archive:
        add_file(archive, ROOT / "installers" / "README-JA.md", f"{archive_root}/README-JA.md")
        add_file(archive, ROOT / "installers" / "README-EN.md", f"{archive_root}/README-EN.md")
        for path in sorted(scripts_root.iterdir()):
            if path.is_file():
                add_file(archive, path, f"{archive_root}/{path.name}")
        write_plugin_payload(archive, f"{archive_root}/payload/emi-guardian", manual_directory)
    return output


def build_all_installers(platform_installers: tuple[Path, ...]) -> Path:
    """Build a convenience archive containing all platform installer ZIPs."""

    output = DIST / f"emi-guardian-{VERSION}-all-platform-installers.zip"
    archive_root = f"emi-guardian-{VERSION}-installers"
    checksum_text = "\n".join(f"{sha256(path)}  {path.name}" for path in platform_installers) + "\n"
    with zipfile.ZipFile(output, "w") as archive:
        for path in platform_installers:
            add_file(archive, path, f"{archive_root}/{path.name}")
        add_bytes(archive, checksum_text.encode("utf-8"), f"{archive_root}/SHA256SUMS-installers")
    return output


def build_source() -> Path:
    """Build the complete source archive under a single root directory."""

    output = DIST / f"kicad-emi-guardian-{VERSION}-source.zip"
    archive_root = f"kicad-emi-guardian-{VERSION}"
    with zipfile.ZipFile(output, "w") as archive:
        for path in sorted(ROOT.rglob("*")):
            if path.is_file() and not excluded(path):
                add_file(archive, path, f"{archive_root}/{path.relative_to(ROOT).as_posix()}")
    return output


def build_demo() -> Path:
    """Generate and archive the synthetic demonstration report."""

    report_dir = DIST / "demo-report"
    if report_dir.exists():
        shutil.rmtree(report_dir)
    generate(report_dir)
    output = DIST / f"emi-guardian-{VERSION}-demo-report.zip"
    with zipfile.ZipFile(output, "w") as archive:
        write_tree(archive, report_dir, "emi-guardian-demo-report")
    return output


def sha256(path: Path) -> str:
    """Return a lower-case SHA-256 digest."""

    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _remove_old_outputs() -> None:
    """Remove release files from a previous local build."""

    DIST.mkdir(parents=True, exist_ok=True)
    for path in DIST.iterdir():
        if path.is_file() and (
            path.suffix in {".zip", ".sha256"} or path.name in {"SHA256SUMS", "BUILD-INFO.json"}
        ):
            path.unlink()


def main() -> int:
    """Validate sources and build every release artifact."""

    validate_plugin_manifest()
    validate_pcm_metadata()
    validate_default_config()
    validate_python_sources()
    validate_release_safety_contracts()
    run_optional_checks()
    _remove_old_outputs()

    manual_directory = DIST / "manuals"
    if manual_directory.exists():
        shutil.rmtree(manual_directory)
    build_manual_files(manual_directory)

    # Keep the source tree's embedded manuals synchronized so the source ZIP
    # and local development tree contain the same documents as every runtime
    # package.
    embedded_manuals = ROOT / "plugin" / "docs"
    if embedded_manuals.exists():
        shutil.rmtree(embedded_manuals)
    shutil.copytree(manual_directory, embedded_manuals)

    manuals = build_user_manuals(manual_directory)
    validate_user_manual_archive(manuals)
    pcm = build_pcm(manual_directory)
    validate_archive(pcm)
    manual = build_manual(manual_directory)
    validate_manual_archive(manual)

    platform_installers = tuple(
        build_platform_installer(platform, manual_directory) for platform in PLATFORMS
    )
    for platform, installer in zip(PLATFORMS, platform_installers):
        validate_installer_archive(installer, platform)
    all_installers = build_all_installers(platform_installers)
    validate_all_installers_archive(all_installers)

    demo = build_demo()
    source = build_source()
    validate_source_archive(source)
    artifacts = (
        pcm,
        manual,
        *platform_installers,
        all_installers,
        source,
        demo,
        manuals,
    )
    checksum_lines = [f"{sha256(path)}  {path.name}" for path in artifacts]
    (DIST / "SHA256SUMS").write_text("\n".join(checksum_lines) + "\n", encoding="utf-8")
    build_info = {
        "version": VERSION,
        "built_at_utc": "2026-08-13T00:00:00Z",
        "artifacts": [
            {"name": path.name, "bytes": path.stat().st_size, "sha256": sha256(path)} for path in artifacts
        ],
    }
    (DIST / "BUILD-INFO.json").write_text(
        json.dumps(build_info, indent=2) + "\n",
        encoding="utf-8",
    )
    for item in build_info["artifacts"]:
        print(f"{item['name']}: {item['bytes']} bytes, sha256={item['sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
